on:
    pull_request_target:
        types: [opened]

jobs:
    add_pr_comment:
        runs-on: ubuntu-latest
        name: 'Comment Checkout Info'
        env:
            PR_NUMBER: ${{ github.event.number }}
            PR_HEAD_REF: ${{ github.head_ref }}
        steps:
            - name: Comment PR
              uses: thollander/actions-comment-pull-request@v1
              with:
                  message: |
                      Use the command(s) below to checkout this specific pull request code:
                      ```sh
                      git fetch origin pull/${{ env.PR_NUMBER }}/head:${{ env.PR_HEAD_REF}}
                      git checkout ${{ env.PR_HEAD_REF}}
                      ```
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
