on:
    pull_request:
        types: [opened]

jobs:
    add_pr_comment:
        runs-on: ubuntu-latest
        name: 'Tell the reviewer how to checkout a branch locally from a PR.'
        env:
            PR_NUMBER: ${{ github.event.number }}
            PR_REPO: ${{ github.event.repository }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Comment PR
              uses: thollander/actions-comment-pull-request@v1
              with:
                  message: |
                      Hello Reviewer(s),
                      If you need to check this out locally try this command.
                      `git fetch origin pull/$PR_NUMBER/head:$PR_REPO`
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
